### ISSUE TITLE
Have multi_image_picker save images and return a list of File objects?

### ISSUE THREAD

**Issue by acherkashyn** [Sh1d0w/multi_image_picker#115]
**Is your feature request related to a problem? Please describe.**
I'm building an app that lets user selects a set of their photos and upload them to the server. Using `Future<ByteData>` that multi_image_picker returns for an original image is possible, but inconvenient. I have to go through the steps of waiting for the future to complete, pull width/height, compress the image into JPEG using another library, then save it onto a local file using still another library. These steps require jumping through some hoops and adding lots of boiler plate code.

**Describe the solution you'd like**
It would be great if multi_image_picker could encapsulate all those steps behind the scenes and return a list of File objects, ready for uploading. There is an example of this in flutter plugin [image_picker](https://pub.dartlang.org/packages/image_picker), which allows to only select 1 photo, but returns a File with the contents of the photo.

**Describe alternatives you've considered**
Described above^^^ Adding heavy infrastructure to await futures for photos, compressing into JPEGs, computing local file paths, writing to files. This is becoming very hard, considering that these steps are CPU intensive so have to be done in a dart isolate, and dart isolates don't support flutter plugins without still another experimental library.

**Additional context**
Given all of the above, it may be more feasible to push all this processing into platform-specific plugin code, where you can use Android/iOS threads and existing libraries for image encoding and writing to file. And add extra methods in multi_image_picker to supply cache path, ability to query the cache, clean the cache, etc.

Have you thought of expanding multi_image_picker in this direction? It would be great to discuss what kind of a solution you think would work for this library.

Thanks!

**Comment by Sh1d0w** [comment]
Hi, this is covered in the [FAQ](https://sh1d0w.github.io/multi_image_picker/#/faq?id=why-the-plugin-don39t-return-image-paths-directly) section.

What the original image picker does, is that it copies the selected image from the device to the temp folder and returns the path. You understand that this is not possible here, since this operation is sync, and if you pick 100 images at once you have to wait like 5 min before you return to the application.

The aim of this plugin is to be fast and efficient, and to provide you with tools out of the box that allows you to quickly display the picked images via thumbs, read the image metadata, or access the original image data in a non blocking way, no matter what count of images you pick.

Can you describe more about your use case? Why you have to save the picked images locally? This plugin already returns all images in JPEG format. It converts them internally before resolving the image data. Also you can provide optional quality parameter so the returned JPGE image is downsampled to this quality. You don't need to save those images to a file system in case you want to display or upload them. This gives you the benefit of not having to use third party plugins or worry about cleaning up after yourself.

**Comment by Sh1d0w** [comment]
Just wanted to add that the initial version of this plugin returned the image paths directly, but this does not worked quite well.

As I said we need to do what the official image picker plugin does - to copy the image to the tmp folder and return it. This is because of several reasons:

1. Now days not all photos live on your device. For example on iOS it stores most of the image on iCloud and removes them in your device leaving only thumb previews. When user picks such image we have first to download it before we can return the original. If we make this sync operation the plugin will become very slow as you pick more images.
2. The original image picker plugin converts all picked images to JPEG before it returns the path. This is what this plugin does as well. Again this is expensive operation and we can not make it sync. The reason for this to be done is because currently Flutter does not have support for all image codes. See this issue I've opened a while ago https://github.com/flutter/flutter/issues/20522

**Comment by Sh1d0w** [comment]
I am going to close this, thanks for using the plugin and I hope you understand the choices made here.
