### ISSUE TITLE
How to remove 2 black bars at 2 edges when creating thumbnails?

### ISSUE THREAD

**Issue by shpy2001** [Sh1d0w/multi_image_picker#117]
How to remove 2 black bars at 2 edges when creating thumbnails?
This means creating compression-resized images without scaling.

**Comment by Sh1d0w** [comment]
Do you mean to crop the image, instead of scaling it? 

On Android I am using [ThumbnailUtils.extractThumbnail](https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L165), which already does this.

On iOS I believe I can pass `resizeMode: PHImageRequestOptionsResizeModeExact` to make it crop it as well, I think currently it scales it.

Can you please confirm if this is the case?

**Comment by shpy2001** [comment]
I mean, when creating thumbnails from a rectangular image, the created thumbnail will have a square with 2 black bars on both sides. I want to ask how to remove those two black bars.

Same as above, now requestOriginal does not have the resize option, how can I just compress and resize the image at the same time?

**Comment by Sh1d0w** [comment]
I don't think this is a problem with the image picker, rather than how you present the image.

Can you give me some example code where I can reproduce what you are trying to say? In [this](https://i.imgur.com/lvN4Hfd.mp4) example I pick a rectangular image and it is displayed correctly in the specified thumb size.

**Comment by shpy2001** [comment]
Oh, I'm sorry, my mistake. I discovered that 2 black bars were created from my camera app.

Besides that, can you provide an image resizing function that still retains the aspect ratio? With image compression option?

Thank you very much.

**Comment by Sh1d0w** [comment]
Sure, just please open a separate issue to track that feature request.

Thanks.
