### ISSUE TITLE
 Uploading images takes a lot of time and memory

### ISSUE THREAD

**Issue by hahai96** [Sh1d0w/multi_image_picker#184]
I am trying to upload some images to the server using byteData, but I think the program takes too much time and memory to convert images into bytes. When uploading multiple images, sometimes my application is suddenly stopped.

I usually take 20s to upload an image if uploaded this way, i try uploading the image via the file path, it only takes about 2 seconds.

Any advice for me, thank you very much.

```
FormData formData = FormData.from({"trip_id": tripId, "typeFile": "image", "file_del": delFiles});
    List<UploadFileInfo> filesUp = List();
    List assets = post?.images ?? [];
    for (int i = 0; i < assets.length; i++) {
      Asset asset = assets[i];
      ByteData byteData = await asset.requestOriginal();
      List<int> imageData = byteData.buffer.asUint8List();
      filesUp.add(UploadFileInfo.fromBytes(imageData, asset.name));
    }

    formData['files'] = filesUp;
  
    return request('POST', ApiNote.togetherCover, headers(token), formData, null);

//Background concurrent copying GC freed 2742(243KB) AllocSpace objects, 8(4MB) LOS objects, 49% free, 15MB/31MB, paused 6.174ms total 62.290ms
```

**Comment by Sh1d0w** [comment]
I suggest you to never do this in a loop. Images, especially original ones can be very large on size (16MB and more). What you are doing here is eating your memory, because you are putting byte data into a big list which again is kept in memory.

What I suggest you instead of uploading all images at once, to upload them one by one so you don't hold all image data in memory. For the UI part you can show some sort of progress bar, indicating how much of total images have been uploaded.
