### ISSUE TITLE
On MIX2 android phone, picker view will not show on first time I used

### ISSUE THREAD

**Issue by chenft** [Sh1d0w/multi_image_picker#199]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android:  Yes

Is it happening on iOS:  No

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**
When MIX2 android phone first installed the app, and want to picked photo, will show request window, no matter what i choosed, it will not show picker view. So i try to select again, and this time it will show an error: PlatformException(already_active, Image picker is already active, null).
Until I kill the app, and retry to picker photo, this time it will success.

**Comment by Sh1d0w** [comment]
What version of the plugin are you using?

**Comment by chenft** [comment]
> What version of the plugin are you using?

I only try two version: 4.3.4 and 4.3.3

**Comment by chenft** [comment]
@Sh1d0w I only try two version: 4.3.4 and 4.3.3.I only find MIX2 phone has this bug, other android not found.

**Comment by Sh1d0w** [comment]
What Android version has this phone?

**Comment by chenft** [comment]
@Sh1d0w android 8.0

**Comment by chenft** [comment]
@Sh1d0w ,maybe I found this bug's real reason. You're plugin is ok.But when I add `imei_plugin: 1.1.0` plugin in pubspec.yaml, your picker will not show after permission request.Even I dont't use imei_plugin, only add this plugin in pubspec. Your plugins maybe have some conflict?

**Comment by Sh1d0w** [comment]
@chenft Thanks for the information. I took a look and it indeed seems the bug is in the `imei_plugin`.

In short both plugins use `PluginRegistry.RequestPermissionsResultListener` to register request permission via `registrar.addRequestPermissionsResultListener `. This is how Flutter suggest to register permissions listener through their system. That's fine.

However the `imei_plugin` has implemented this incorrectly. See [this](https://github.com/kevincaicedo/imei_plugin/blob/master/android/src/main/java/com/rioapp/demo/imeiplugin/ImeiPlugin.java#L91) line they return true if the request is not related to their plugin, however they need to return false. This is because in if you look into the source code for the Flutter plugin registry [here](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/app/FlutterPluginRegistry.java#L194), you will see that if any of the registered listeners return true, the others will not be triggered.

Which is the case here, the `imei_plugin` permission listener is triggered first when you pick image, it checks the code, it is not related to it and should return false, but it returns true. And my permission listener is never invoked.

Please open an issue in their repository to fix this, I am going to close the issue here.

**Comment by chenft** [comment]
@Sh1d0w thanks a lot!
