### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by sh0umik** [Sh1d0w/multi_image_picker#260]
Is there any chance to have for the web ? I am using multi_image_picker in all of my flutter projects. Web support would be much appreciated

**Comment by Sh1d0w** [comment]
For sure I would like to support web as well, but so far I haven't found a good guide how we can integrate with web. Flutter official documentation includes guides only for iOS / Android [here](https://flutter.dev/docs/development/packages-and-plugins/developing-packages).

I haven't followed the flutter web progress closely, but once it reaches stable state and have a good documentation how to create / integrate plugins for it I will look into it.

PRs are also welcome.

**Comment by sh0umik** [comment]
I am looking to the solution mentions here

https://github.com/flutter/flutter/issues/36281#issuecomment-514608895

But I was wondering how it would fit in Asset. Specially the identifier/path parameter.

**Comment by lehno** [comment]
I would say that there are more docs about web version now, cam you check that> it would be great for my project

**Comment by Sh1d0w** [comment]
PRs are always welcome, you know it is an open source project, you don’t have to rely on me to implement it.

**Comment by lehno** [comment]
I'm still learning, when I have exp to build stable plugins for the community, I will do. Thank you

**Comment by deakjahn** [comment]
@Sh1d0w yes, sure. :-) The only problem is that to add proper web support, the plugin itself should be reorganized as a [federated plugin.](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins) And you probably won't like that so much. :-)

With a federated plugin, people can independently work on the web (or any other platform later) plugin, and when done, you can simply point to the new plugin as the recommended one (or take it over completely, of course) and the system will do the rest: it will use whatever version is needed in a cross platform app. Without that, just by using PRs in the current plugin, it's very easy (if not completely impossible) to separate web and non-web code so that the separation satisfies the compiler.
