### ISSUE TITLE
HEIC format

### ISSUE THREAD

**Issue by malikdoksoz** [Sh1d0w/multi_image_picker#268]
multi_image_picker version: 4.5.6

Is it happening on Android: No

Is it happening on iOS: Yes

iOS version: 13.1

`[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G103, locale
    tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!`

**Error from XCODE:** 

`2019-09-30 16:38:24.665133+0300 Runner[460:36344] flutter: 375.0
2019-09-30 16:38:40.876939+0300 Runner[460:36344] flutter: 375.0
2019-09-30 16:38:43.736220+0300 Runner[460:36102] <_UISystemGestureGateGestureRecognizer: 0x2813f4960>: Gesture: Failed to receive system gesture state notification before next touch
2019-09-30 16:38:59.679777+0300 Runner[460:36344] flutter: Another exception was thrown: Exception: Could not instantiate image codec.
2019-09-30 16:38:59.746625+0300 Runner[460:36344] flutter: Another exception was thrown: Exception: Could not instantiate image codec.
2019-09-30 16:38:59.812335+0300 Runner[460:36344] flutter: Another exception was thrown: Exception: Could not instantiate image codec.
`

**Error from vscode:** 

`
════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack
#0      _futurize  (dart:ui/painting.dart:4134:5)
#1      instantiateImageCodec  (dart:ui/painting.dart:1669:10)
#2      PaintingBinding.instantiateImageCodec 
package:flutter/…/painting/binding.dart:74
#3      FileImage._loadAsync 
package:flutter/…/painting/image_provider.dart:545
<asynchronous suspension>
...
Path: /var/mobile/Media/DCIM/107APPLE/IMG_7598.HEIC`

**How can i convert HEIC formats to jpg and showing in the widget.**

**Comment by Sh1d0w** [comment]
See the example app in this repo. You can use `getByteData` or `getThumbData` on the asset instance to get the image data in JPEG. Please read the documentation of this plugin, it is well explained there.

The issue you are seeing is because Flutter does not have yet a code for HEIC images, I've reported this a long time ago here https://github.com/flutter/flutter/issues/20522

**Comment by malikdoksoz** [comment]
Cool, How do I use the formats you say? I've reviewed the documentation, but can you give me a little example of how to use it as an image path?

**Comment by Sh1d0w** [comment]
You can’t  use the image path directly in an image widget as I said flutter does codecs for it yet.

See the example app you can use the image widget with ByteData and there is handy widget to display thumbs provided in this repo.

**Comment by malikdoksoz** [comment]
There is no problem in the image picker library in heic format, can your library convert?

**Comment by Sh1d0w** [comment]
No this is not possible. The single image picker does that since you pick only one image. It creates a new jpeg image in the temp directory . But with this library you can pick thousands of images, it is not feasible to flood the temp directory with that many images that you may never use. Also not to mention that there will be significant delay in that depending on how many images you pick. Especially on iOS where the image is not guaranteed to be on the device but in iCloud and have to be downloaded first.

That’s why there are those two methods that I’ve suggested you to obtain the image data asynchronously whenever you need it.

**Comment by malikdoksoz** [comment]
You are true. I need 3 pictures, for example, it can be limited to 15 pictures.  This can be solved with the temp folder cleaning function when we are done with the pictures we use.  I'd like you to add it as an optional feature.

**Comment by Sh1d0w** [comment]
Unfortunately I am not convinced I would like to do and maintain this. The problem is temporary fixed with the `getByteData` and `getThumbByteData` until Flutter supports the HEIC codec. You can use those methods.

Also you can fork this repo and implement it yourself, nothing is stopping you :)

**Comment by malikdoksoz** [comment]
If I knew swift, I wouldn't tire you.  Thank you for the answer :)
