### ISSUE TITLE
Help! Cannot retrieve length of file on error on ios.

### ISSUE THREAD

**Issue by ShshyDevooo** [Sh1d0w/multi_image_picker#319]
**Bug Report**

`multi_image_picker` version: 
4.5.9
Is it happening on Android: 
no
Is it happening on iOS: 
yes
```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**
I pick up an image and get the file path on ios. When i use this path to upload to server but the error comes out.
Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = '/var/mobile/Media/DCIM/100APPLE/IMG_0459.PNG' (OS Error: Operation not permitted, errno = 1)

**Comment by Sh1d0w** [comment]
Hi,

this seems to be caused by a recent change in iOS 13 [see here](https://stackoverflow.com/questions/57798968/didfinishpickingmediawithinfo-returns-different-url-in-ios-13/58099385#58099385)

Since this is the case I will remove the direct access to url from this plugin soon.

In order to upload your images please follow the example in the docs, it will work https://sh1d0w.github.io/multi_image_picker/#/upload
