### ISSUE TITLE
Make File from Asset

### ISSUE THREAD

**Issue by kleinpetr** [Sh1d0w/multi_image_picker#349]
Is there some chance to make File() from Asset() or get path of image?

**Comment by Sh1d0w** [comment]
Yes, you can obtain the ByteData from the asset and save it to a file at whatever place you want.

**Comment by kleinpetr** [comment]
Yes I know. thats I am using now. But I have universal component for choosing images from android via another plugin and this plugin I am using only for iOS. and the result of my component is List of Files() then I show selected files to user, everything ok, but when I choose 20 images in hight resolution and then creating files by stream, sometimes totally kill the iPhone and need restart.

**Comment by Sh1d0w** [comment]
That's the case, because the library allows you to pick thousand of images it is not possible to get a file directly (see https://github.com/Sh1d0w/multi_image_picker/issues/337#issuecomment-563581173 why).

I suggest you to revise your code to optimize it and request image data only when is needed, not exactly after images are picked.
