### ISSUE TITLE
AssetView not reloading

### ISSUE THREAD

**Issue by kanulp** [Sh1d0w/multi_image_picker#36]
Hi Radoslav, 
    Thank you for this amazing package. 

I have issue regarding assetview. As you can see in GIF first of all I'm selecting 5 different images from gallery, then when i click on any image(clicking on first image in GIF) i want to remove it from grid and update the list as described in GIF which for assetview not working but for text(assetview's identifier string or assert path )
it is working as expected. Am I missing something in logic or it's bug in assetview ?

In both the cases i'm tapping on 1st image. so the corresponding 2nd image should come to first. which is shown in string case.

![11](https://user-images.githubusercontent.com/13494911/50026713-eb145b00-000f-11e9-9a06-47f3bff19dfe.gif)

code link - https://gist.github.com/kanulp/7ca984e52669ee8bf063c57d5b91104f

[https://gist.github.com/kanulp/7ca984e52669ee8bf063c57d5b91104f](url)

**Comment by Sh1d0w** [comment]
Hi @kanulp and thanks for using the plugin.

In order to understand why your code does not work, you first need to understand how Flutter Stateless, Stateful and Inherited widgets work. Here is a good explanation video from one of the developers working on Flutter, give it a try

https://www.youtube.com/watch?v=kn0EOS-ZiIc

After you watch it you will see that in short, AssetView has its own state, and removing items from the array of images preserve that state at the position of the element. You can put keys if you plan to modify the items in the grind in order to properly replace the state as well, as explained in the video.
