### ISSUE TITLE
Support for BitCode

### ISSUE THREAD

**Issue by AlexVincent525** [Sh1d0w/multi_image_picker#368]
**Bug Report**

`multi_image_picker` version: `4.6.0`

Is it happening on Android: No

Is it happening on iOS: **Yes**

**Describe the bug**

When `Enable Bitcode` set to `true`, building on the iOS side failed.

```
ld: '/Users/alex/SomeFlutterProject/build/ios/Release-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.framework/BSGridCollectionViewLayout' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/alex/SomeFlutterProject/build/ios/Release-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.framework/BSGridCollectionViewLayout' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I thought the actual usage of `BSGridCollectionViewLayout` might be the `BSImagePicker`, but it's related to your packages, so could you help with this investigation? Thx.

**Comment by Sh1d0w** [comment]
Hi. This class is used internally by BSImagePicker to build the grid of images and not explicitly by the plugin.

As I am not too sure how I can help you in that case, you can try asking in the official BSImagePicker repo.

**Comment by AlexVincent525** [comment]
I'm really love your quick reply. 😃

**Comment by AlexVincent525** [comment]
![image](https://user-images.githubusercontent.com/15884415/72672951-bdfd6c00-3a9d-11ea-8479-a163fa46c87f.png)

Idk why this happened, but with this I cannot use bitcode for build flutter app...Could you help me to ask why he did this?

**Comment by AlexVincent525** [comment]
https://github.com/mikaoj/BSImagePicker/issues/234 
https://github.com/mikaoj/BSGridCollectionViewLayout/issues/11

**Comment by AlexVincent525** [comment]
Seems like he just closed the entire issue section for BSImagePicker.

**Comment by AlexVincent525** [comment]
He gives an update with bitcode support (3.0.0), can you test it when you have some spare time to see if it worked? Thx. https://github.com/mikaoj/BSGridCollectionViewLayout/issues/11#issuecomment-575961165

**Comment by Sh1d0w** [comment]
Hi @AlexVincent525 

I was just going to release a RC version for you with version 3 of BSImagePicker while I saw this

<img width="591" alt="Screenshot 2020-01-19 at 6 11 55" src="https://user-images.githubusercontent.com/5074917/72674719-aebcf500-3a82-11ea-899f-188f204df74f.png">

Seems like he dropped support for taking images in version 3 which will be a breaking change in my plugin if I update. 

If taking photos is not important from you from the picker you can fork this repo and use version 3 of BSImagePicker.

Meanwhile I am considering switching to another native iOS image picker library instead of BSImagePicker because of this and the attitude of the developer. Will do some research before that so I can find the most reliable and useful one.

Thanks for your patience!

**Comment by AlexVincent525** [comment]
I've already split these two feature in different entries, I'll try it once you release and come back to you. 👍

**Comment by dheeraj2dj** [comment]
Any temporary resolution with this issue? Having the same issue :-/
<img width="1280" alt="Screenshot 2020-06-26 at 12 23 28 AM" src="https://user-images.githubusercontent.com/2561485/85781436-4d8d0200-b743-11ea-9d5e-a5a48e5d1554.png">
