### ISSUE TITLE
Large Image on ios causes out of memory exception?

### ISSUE THREAD

**Issue by PritishSawant** [Sh1d0w/multi_image_picker#400]
multi_image_picker` version:^4.6.2
Is it happening on Android:  Yes 

Is it happening on iOS: Yes 

flutter doctor output:

Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,

    locale en-IN)

 

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)

[✓] Android Studio (version 3.6)

[✓] VS Code (version 1.42.1)

Whenever i add an image of high pixels from my image library and try to view it by keeping its original width and height i get an error saying Out of memory exception. I tried reducing the quality to 50 but i still gets the issue on ios.
For Android it takes a lot of time to preview the added image, the image does not get displayed for 4 to 5 seconds even after the progress bar disappers. This is the same issue for ios as well.

**Comment by Sh1d0w** [comment]
You should never display the full sized image in your app, always use thumbs.

Reason is that in most cases you don't need the full sized images, unless you are presenting the image in full screen, otherwise try to request suitable size of the image to the area where you will use the image.

Most images taken with HD resolution can easily be 10+ MB of size. Since each time you request image data it loads it in the memory, and let's say you do this in a loop, you can easily get out of memory pretty fast.

Requesting a thumb with correct size of your use case however can lower the size of data in the memory to several kilobytes and will be very fast.

One case where you will need the original image will be if you are uploading it to a sever, then you can request the original image data, but you need to make sure you are doing it on batches so you don't end with OOM again.

**Comment by PritishSawant** [comment]
@Sh1d0w I am trying to display the original image in AssetThumb as well but i am keeping the widht and height as original. Should i be doing any thing else?

**Comment by Sh1d0w** [comment]
Alright, can you provide more info then, best case will be some example code which I can checkout and run and also some of the images you are trying to display and that gives you the error?

Are you displaying multiple images in a list, or it crashes even on a single image? Are you running the app on a simulator or a real device?

**Comment by PritishSawant** [comment]
I am running on a real device. I am trying to display images in a list. Here is the proper flow which i am implementing. User will pick list of images from file explorer. I am displaying list of those image as a thumbnail in a gridview builder. On clicking on any of those image, all the added images should be shown in a slide show. So following is my code to display images in slideshow

```
PageView.builder(
                            itemBuilder: (context, index) {
                              return Padding(
                                padding: const EdgeInsets.all(8),
                                child:Column(
                                  children: <Widget>[
                                 
                                    AssetThumb(
                                      asset: patientSlideShowBloc
                                          .imageListValue[index].img,
                                      width: patientSlideShowBloc
                                          .imageListValue[index]
                                          .img
                                          .originalWidth,
                                      height: patientSlideShowBloc
                                          .imageListValue[index]
                                          .img
                                          .originalHeight,
                                   
                                    ),
                                  
                                  ],
                                )
```

I have downloaded high quality images from unsplash. you can checkout those images. Thank you for the quick reply

**Comment by PritishSawant** [comment]
@Sh1d0w Here is a temporary work around i found. Its not exactly a solution

I decide to divide the original width and height by 5 and set the quality to 50. I know this not really a great solution, but seems to be working for me. Also if we just reduce the quality and keep the original width and height or vice versa the quality of image does not reduce

**Comment by Sh1d0w** [comment]
You can't see the difference if quality with naked eye if you set the value between 50 and 100, the difference is only in the size of the image.

**Comment by PritishSawant** [comment]
@Sh1d0w If i keep original width and height and change quality to 10 still i dont see any change in quality

**Comment by iamsandeepsk** [comment]
so the solution is to decrease the quality of image ?

**Comment by Sh1d0w** [comment]
The solution depends on the cause of the error.

Generally the plugin returns ByteData, which is basically the content of the image. If you are requesting a lot of images in a loop, or very large images that causes OOM, because you are keeping reference to the byte data you can avoid that by either displaying thumbs, or if you for some reason need the original image you can request the byte data, save to a temporary file and use that file instead and then free the allocated byte data.

I can't help you further with that unless you provide example code that triggers such OOM so I can actually see what you are doing.
