### ISSUE TITLE
Flutter 1.12 May return null if the flutter has not been added to the Activity

### ISSUE THREAD

**Issue by charlesYun** [Sh1d0w/multi_image_picker#456]
![image](https://user-images.githubusercontent.com/15682437/81463219-599c1f00-91ea-11ea-8c17-f19a2faf96f0.png)

**Comment by chenglei1986** [comment]
@caoyunxiao 

If you are using a cached engine, replace
```java
FlutterEngine flutterEngine = new FlutterEngine(context);
```
with
```java
FlutterEngine flutterEngine = new FlutterEngine(context, null, false);
```
so that the plugins will not be registered automatically until FlutterActivity is started.

**Comment by caoyunxiao** [comment]
I can't find it, so why not consider upgrading the framework?  @chenglei1986

**Comment by caoyunxiao** [comment]
New FlutterEngine(context, null, false) will report an error, which may have something to do with my use of the framework flutter_boost. Why not consider upgrading the multi_image_picker framework to solve this problem?


On 05/21/2020 11:36，Darren<notifications@github.com> wrote：

@caoyunxiao

If you are using a cached engine, replace

FlutterEngine flutterEngine =newFlutterEngine(context);

with

FlutterEngine flutterEngine =newFlutterEngine(context, null, false);

so that the plugins will not be registered automatically until FlutterActivity is started.

**Comment by Sh1d0w** [comment]
@caoyunxiao This is an open source project so feel free to debug and provide a PR that fixes the issue.

**Comment by Sh1d0w** [comment]
Should be fixed now https://github.com/Sh1d0w/multi_image_picker/pull/505
