### ISSUE TITLE
Done button is not localized from system localization

### ISSUE THREAD

**Issue by zxstarxing** [Sh1d0w/multi_image_picker#468]
**Bug Report**

`multi_image_picker` version:  ^4.6.7
Is it happening on Android: 
No
Is it happening on iOS: 
Yes

look here https://github.com/mikaoj/BSImagePicker/issues/249

Please update the IOS plugin version

thanks

**Comment by Sh1d0w** [comment]
Unfortunately I can't upgrade the version to 3+ because the author of BSImagePicker created breaking change in version 3 by removing the option to take images from the gallery.

I considered to migrate from BSImagePicker to another picker that has same functionalities but is more customisable and well maintained, you can follow this issue and see when it will be implemented https://github.com/Sh1d0w/multi_image_picker/issues/373
