### ISSUE TITLE
Nullsafety support

### ISSUE THREAD

**Issue by Teutonic-Knight-0** [Sh1d0w/multi_image_picker#630]
Please migrate to null safety.

**Comment by Sh1d0w** [comment]
It is an open source project, feel free to open a PR with implementation and I will review it.

**Comment by SametSahin10** [comment]
> It is an open source project, feel free to open a PR with implementation and I will review it.

Hmm, I'm surprised that your response was to comment and close the issue while you could use this very issue to keep track of null safety support. That way people would have known that there's an issue about null safety support rely on that for the updates. Can you please reopen this so that people use it as reference while submitting their PR's?

**Comment by fzyzcjy** [comment]
I have made a PR: https://github.com/Sh1d0w/multi_image_picker/pull/634
