### ISSUE TITLE
URGENT: Please help here . Unable to generate signed apk 

### ISSUE THREAD

**Issue by krsolutions** [Sh1d0w/multi_image_picker#85]
Could not find com.github.Sh1d0w:Matisse:1.0.0.
Searched in the following locations:
  - file:/Users/reddy/Library/Android/sdk/extras/m2repository/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.pom
  - file:/Users/reddy/Library/Android/sdk/extras/m2repository/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.jar
  - file:/Users/reddy/Library/Android/sdk/extras/google/m2repository/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.pom
  - file:/Users/reddy/Library/Android/sdk/extras/google/m2repository/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.jar
  - file:/Users/reddy/Library/Android/sdk/extras/android/m2repository/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.pom
  - file:/Users/reddy/Library/Android/sdk/extras/android/m2repository/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.jar
  - file:/Users/reddy/.m2/repository/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.pom
  - file:/Users/reddy/.m2/repository/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.jar
  - https://repo.maven.apache.org/maven2/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.pom
  - https://repo.maven.apache.org/maven2/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.jar
  - https://maven.google.com/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.pom
  - https://maven.google.com/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.jar
  - http://dl.bintray.com/jlmd/maven/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.pom
  - http://dl.bintray.com/jlmd/maven/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.jar
  - https://jcenter.bintray.com/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.pom
  - https://jcenter.bintray.com/com/github/Sh1d0w/Matisse/1.0.0/Matisse-1.0.0.jar
Required by:
    project :app > project :multi_image_picker

**Comment by Sh1d0w** [comment]
I am not able to reproduce this.

Please provide more info how to reproduce, or better an example repository where I can reproduce this issue. 

Without any more info, I can not help you. Also please follow the issue template when opening an issue.

**Comment by fcu-d0542397** [comment]
I have the same problem

android/build.gradle:
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


android/app/build.gradle:
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.class_6"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
gradle-wrapper.properties:
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

gradle.properties:
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536M


pubspec.yaml:
name: class_6
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  multi_image_picker: ^3.0.11 

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by Sh1d0w** [comment]
@fcu-d0542397 You are using version multi_image_picker: ^3.0.11, which is very old and not actively supported anymore. Please use the latest version which is 4.5.2 and read before that the docs what setup you need.

**Comment by thanvandh4435** [comment]
Just go to project/android/app/build.gradle and check for something like

"minSdkVersion 16"

Here replace 16 with 19
That's it
