### ISSUE TITLE
Saving Images/Asset offline

### ISSUE THREAD

**Issue by sh0umik** [Sh1d0w/multi_image_picker#89]
How can i achieve saving images as draft or saving Asset as draft (offline) like instagram. So that when i reopen the app i can load Asset class from Shared Preference and reload the image.

Can it be done ? Some solution in the Stack-overflow says save the file path in shared_preference and retrieve it when the app loads . Can it be done with Asset class ? I can see a path called Identifier in Asset class and the doc says its not a path but the issue is complicated.

Can i save the identifier and if i do, how to rebuild the Asset class with the identifier and re request the image ?

**Comment by Sh1d0w** [comment]
Yes you can save the identifier as a string in shared preferences and later on when you retrieve it you can manually create new Asset class, passing the identifier.

As the doc says you can't use the identifier as a path, because on Android it is the Content URI to the image and on iOS it is the PHAsset ID. The only proper way to be able to fetch the image data is to reconstruct the asset class with the identifier and then use it's methods to retrieve the data.

**Comment by sh0umik** [comment]
This is not working as expected .. I have saved `identifier`, `name`, `originalWidth`, and `originalHeight` in shared_preference as required by Asset Class and the Build the Asset Class by passing those value

```
            List<Asset> images = <Asset>[];
            item.tempImageInfo.forEach((saved) {
              images.add(Asset(saved.identifier,
                  saved.identifier, saved.width, saved.height));
            });
            oldInfo.willUploadImages = images;
```
 
But when i call thumbData or originalData i get `The getter 'buffer' was called on null.` That makes sense because I was just passing params to a Constructor but Even when i called requestThumbnail() or requestOriginal() before getting the buffer i still get the same error!

Is there any process i am doing wrong?

**Comment by Sh1d0w** [comment]
@sh0umik please provide the full code where you are requesting the image data. It seems like you are not waiting for the Future to resolve when you are accessing the buffer?

**Comment by sh0umik** [comment]
Great :) , thats exactly the issue was .. Solved it via `async` and `await` .. 
```
    for (var image in _assets) {
      await image.requestThumbnail(250, 200, quality: 80);
    }
    await addToStream(_assets);
```

@Sh1d0w  thank you so much for replying so quickly.

**Comment by Sh1d0w** [comment]
@sh0umik I would advise to not do this in a loop, because as many images you pick the longer you will wait in this method and you will block the renderer. Instead take a look into the example folder of this repository to implement an asset preview widget where you load the image data, meanwhile presenting a placeholder for asset. It will also help you to properly de allocate the thumb data when the widget is destroyed, otherwise you can run out of memory pretty quickly with your approach :)
