### ISSUE TITLE
Feel lag when you select a lot of images 

### ISSUE THREAD

**Issue by CircleCurve** [Sh1d0w/multi_image_picker#9]
**Describe the bug**
When you select a lot of photos (up to 50-60), show it into AssetView. It feels lag when scroll up and down

**To Reproduce**
1. open an example
2. open gallery
3. select more than 50 photos 
4. click done on top right hand side
5. see what you have selected

**Comment by Sh1d0w** [comment]
I've been testing this a lot on my physical phones, with more than 200 selected at a time and can't feel delay or lag.

Naturally the requestThumb or requestOriginal methods are async meaning they will need some time when executed to return the data. So it is advised to call them as soon as you need the images. Also request thumb as small thumb sized as you need, don't request large sizes if you don't need them.

Also when displaying images with `Image.memory` widget, don't forget to se `gaplessPlayback: true`. This will make following re-renders of the widget no blinking if the data is already loaded. I've actually forgot to put that in the example will update it now.

Also you can implement something like loading spinner placeholder to show before the image is loaded.

**Comment by CircleCurve** [comment]
I'm using requestOriginal for my own project because requestThumbNail is too blur and hardly to see the image. But when i use requestOriginal instead of requestThumbNail, there is a high possibility appear out of memory exception and force quit application. Maybe we can add a compression rate for image?

**Comment by Sh1d0w** [comment]
The best solution will be to return just the file path so you can display it with `Image.file` widget, instead of `Image.memory`. This can be implemented on Android, but unfortunately for iOS currently flutter does not support HEIC format, which from iOS 11 is the default image format when you take pictures with camera. Until flutter implements support for HEIC codec, I do not plan to return image paths.

I've already opened issue in their issue tracker [here](https://github.com/flutter/flutter/issues/20522). Once it is implemented I will add the file path in the asset class as well, so if you just need to display the original image it will be easier.

**Comment by CircleCurve** [comment]
Thank you for open this issue. I have also added below code in example. AutomaticKeepAliveClientMixin can prevent an AssetState widget clean in garbage collection. When you scroll up or down, it will first load from memory cache. No need to re-create widget again
```dart
class AssetState extends State<AssetView> with AutomaticKeepAliveClientMixin<AssetView>
  @override
  bool get wantKeepAlive => true;
```

**Comment by CircleCurve** [comment]
There is reference link. I think we can add it in example
[](https://medium.com/@diegoveloper/flutter-persistent-tab-bars-a26220d322bc)

**Comment by Sh1d0w** [comment]
@CircleCurve Thank you for the link, I wasn't aware of that. Will update the example.

**Comment by Sh1d0w** [comment]
I will close this now. Also added a FAQ section in the readme explaining how and why the plugin works this way https://github.com/Sh1d0w/multi_image_picker#faq
