### ISSUE TITLE
Glide dependency conflict with Google Places SDK

### ISSUE THREAD

**Issue by Morfilio** [Sh1d0w/multi_image_picker#94]
**Bug Report**

`multi_image_picker` version: 3.0.23

Is it happening on Android: Yes
Is it happening on iOS:  No

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.13, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!
```

**Describe the bug**

My Android build is failing:
D8: Program type already present: com.bumptech.glide.ListPreloader$PreloadModelProvider
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Program type already present: com.bumptech.glide.ListPreloader$PreloadModelProvider

I found out that there is a conflict with 'com.google.android.libraries.places:places:1.0.0' which uses com.github.bumptech.glide:glide:4.3.1 . 

The app builds if i change your glide version from 3.8 to 4.x, but it breaks the code.

A workaround is to use a previous version of Google Places SDK.

**Comment by Sh1d0w** [comment]
@Morfilio Thanks for the report. Unfortunately the Android image picking library I am using is not very actively maintained. I've forked it in order to resolve some issues myself, but I can not keep up with all bugs that comes out.

I am thinking to use another Android image picking library that is actively maintained, has similar features as the current one and is more easy to be implemented when installing the Flutter package as it does not require XML overriding, but instead all parameters can be passed in the calling function just like on iOS.

This will solve a lot of problems, including this one I guess.

This is the library I am talking about https://github.com/sangcomz/FishBun

I will keep this issue open and will close it once I made those changes. I hope I can find time soon, as I am currently very busy. PRs are also welcome.

**Comment by Sh1d0w** [comment]
I've just released version 4 of this plugin, which switches from Matisse to FishBun, thanks to @derTuca for the PR!

You should not have problems overriding this now with dependency resolution as FishBun uses glide 4.9.0, in case there is still a problem, please let me know.
